[36m[2023-08-31 09:34:29 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-08-31 09:34:29 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-08-31 09:34:29 DEBUG] [cli:119][39m Using settings file '/Users/collinsorighose/.chaostoolkit/settings.yaml'
[36m[2023-08-31 09:34:30 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/Users/collinsorighose/.chaostoolkit/settings.yaml'.
[36m[2023-08-31 09:34:30 DEBUG] [__init__:450][39m No controls to apply on 'loader'
[36m[2023-08-31 09:34:30 DEBUG] [__init__:450][39m No controls to apply on 'loader'
[36m[2023-08-31 09:34:30 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-08-31 09:34:30 DEBUG] [caching:35][39m Cached 1 activities
[32m[2023-08-31 09:34:30 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-08-31 09:34:30 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-08-31 09:34:30 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-08-31 09:34:30 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-08-31 09:34:30 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-08-31 09:34:30 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-08-31 09:34:30 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-08-31 09:34:30 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-08-31 09:34:30 DEBUG] [caching:35][39m Cached 1 activities
[36m[2023-08-31 09:34:30 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-08-31 09:34:30 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-08-31 09:34:30 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-08-31 09:34:30 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2023-08-31 09:34:30 INFO] [run:369][39m Running experiment: attach-a-policy
[36m[2023-08-31 09:34:30 DEBUG] [__init__:64][39m Initializing controls
[32m[2023-08-31 09:34:30 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-08-31 09:34:30 INFO] [run:400][39m Rollbacks strategy: default
[32m[2023-08-31 09:34:30 INFO] [run:408][39m No steady state hypothesis defined. That's ok, just exploring.
[36m[2023-08-31 09:34:30 DEBUG] [__init__:450][39m No controls to apply on 'experiment'
[32m[2023-08-31 09:34:30 INFO] [run:684][39m Playing your experiment's method now...
[36m[2023-08-31 09:34:30 DEBUG] [__init__:450][39m No controls to apply on 'method'
[36m[2023-08-31 09:34:30 DEBUG] [__init__:450][39m No controls to apply on 'activity'
[32m[2023-08-31 09:34:30 INFO] [activity:215][39m Probe: attach-role-policy
[36m[2023-08-31 09:34:30 DEBUG] [python:33][39m Activity 'attach-role-policy' loaded from '/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/chaosaws/iam/actions.py'
[36m[2023-08-31 09:34:30 DEBUG] [__init__:76][39m Using AWS region 'eu-west-2'
[36m[2023-08-31 09:34:30 DEBUG] [__init__:85][39m Client will be using profile 'default' from boto3 session
[36m[2023-08-31 09:34:32 DEBUG] [activity:237][39m   => succeeded with '{'ResponseMetadata': {'RequestId': 'a1648e11-9ebd-4ddd-8f65-ff9f6b17862c', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'a1648e11-9ebd-4ddd-8f65-ff9f6b17862c', 'content-type': 'text/xml', 'content-length': '212', 'date': 'Thu, 31 Aug 2023 08:34:31 GMT'}, 'RetryAttempts': 0}}'
[36m[2023-08-31 09:34:32 DEBUG] [__init__:450][39m No controls to apply on 'activity'
[36m[2023-08-31 09:34:32 DEBUG] [__init__:450][39m No controls to apply on 'method'
[32m[2023-08-31 09:34:32 INFO] [run:964][39m Let's rollback...
[36m[2023-08-31 09:34:32 DEBUG] [__init__:450][39m No controls to apply on 'rollback'
[32m[2023-08-31 09:34:32 INFO] [rollback:31][39m No declared rollbacks, let's move on.
[36m[2023-08-31 09:34:32 DEBUG] [__init__:450][39m No controls to apply on 'rollback'
[32m[2023-08-31 09:34:32 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-08-31 09:34:32 DEBUG] [__init__:450][39m No controls to apply on 'experiment'
[36m[2023-08-31 09:34:32 DEBUG] [__init__:103][39m Cleaning up controls
[36m[2023-08-31 09:34:32 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-08-31 09:35:37 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-08-31 09:35:37 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-08-31 09:35:37 DEBUG] [cli:119][39m Using settings file '/Users/collinsorighose/.chaostoolkit/settings.yaml'
[36m[2023-08-31 09:35:38 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/Users/collinsorighose/.chaostoolkit/settings.yaml'.
[36m[2023-08-31 09:35:38 DEBUG] [__init__:450][39m No controls to apply on 'loader'
[36m[2023-08-31 09:35:38 DEBUG] [__init__:450][39m No controls to apply on 'loader'
[31m[2023-08-31 09:35:38 ERROR] [cli:268][39m Path "attach-policy.jsonclear" does not exist.
[36m[2023-08-31 09:35:38 DEBUG] [cli:269][39m Path "attach-policy.jsonclear" does not exist.
[36m[2023-08-31 09:39:01 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-08-31 09:39:01 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-08-31 09:39:01 DEBUG] [cli:119][39m Using settings file '/Users/collinsorighose/.chaostoolkit/settings.yaml'
[36m[2023-08-31 09:39:02 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/Users/collinsorighose/.chaostoolkit/settings.yaml'.
[36m[2023-08-31 09:39:02 DEBUG] [__init__:450][39m No controls to apply on 'loader'
[36m[2023-08-31 09:39:02 DEBUG] [__init__:450][39m No controls to apply on 'loader'
[36m[2023-08-31 09:39:02 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-08-31 09:39:02 DEBUG] [caching:35][39m Cached 1 activities
[32m[2023-08-31 09:39:02 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-08-31 09:39:02 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-08-31 09:39:02 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-08-31 09:39:02 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-08-31 09:39:02 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-08-31 09:39:02 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-08-31 09:39:02 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-08-31 09:39:02 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-08-31 09:39:02 DEBUG] [caching:35][39m Cached 1 activities
[36m[2023-08-31 09:39:02 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-08-31 09:39:02 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-08-31 09:39:02 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-08-31 09:39:02 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2023-08-31 09:39:02 INFO] [run:369][39m Running experiment: create-a-policy
[36m[2023-08-31 09:39:02 DEBUG] [__init__:64][39m Initializing controls
[32m[2023-08-31 09:39:02 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-08-31 09:39:02 INFO] [run:400][39m Rollbacks strategy: default
[32m[2023-08-31 09:39:02 INFO] [run:408][39m No steady state hypothesis defined. That's ok, just exploring.
[36m[2023-08-31 09:39:02 DEBUG] [__init__:450][39m No controls to apply on 'experiment'
[32m[2023-08-31 09:39:02 INFO] [run:684][39m Playing your experiment's method now...
[36m[2023-08-31 09:39:02 DEBUG] [__init__:450][39m No controls to apply on 'method'
[36m[2023-08-31 09:39:02 DEBUG] [__init__:450][39m No controls to apply on 'activity'
[32m[2023-08-31 09:39:02 INFO] [activity:215][39m Probe: create-a-new-policy
[36m[2023-08-31 09:39:02 DEBUG] [python:33][39m Activity 'create-a-new-policy' loaded from '/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/chaosaws/iam/actions.py'
[36m[2023-08-31 09:39:02 DEBUG] [__init__:76][39m Using AWS region 'eu-west-2'
[36m[2023-08-31 09:39:02 DEBUG] [__init__:85][39m Client will be using profile 'default' from boto3 session
[36m[2023-08-31 09:39:03 DEBUG] [activity:294][39m Activity failed
    Traceback (most recent call last):
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/chaosaws/iam/actions.py", line 27, in create_policy
        return client.create_policy(
               ^^^^^^^^^^^^^^^^^^^^^
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/botocore/client.py", line 530, in _api_call
        return self._make_api_call(operation_name, kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/botocore/client.py", line 960, in _make_api_call
        raise error_class(parsed_response, operation_name)
    botocore.errorfactory.EntityAlreadyExistsException: An error occurred (EntityAlreadyExists) when calling the CreatePolicy operation: A policy called newer-chaos-policy-for-collins already exists. Duplicate names are not allowed.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/chaoslib/provider/python.py", line 56, in run_python_activity
        return func(**arguments)
               ^^^^^^^^^^^^^^^^^
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/chaosaws/iam/actions.py", line 34, in create_policy
        raise FailedActivity(f"failed creating a policy: {str(x)}")
    chaoslib.exceptions.ActivityFailed: failed creating a policy: An error occurred (EntityAlreadyExists) when calling the CreatePolicy operation: A policy called newer-chaos-policy-for-collins already exists. Duplicate names are not allowed.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/chaoslib/activity.py", line 287, in run_activity
        result = run_python_activity(activity, configuration, secrets)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/chaoslib/provider/python.py", line 58, in run_python_activity
        raise ActivityFailed(
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/chaoslib/provider/python.py", line 56, in run_python_activity
        return func(**arguments)
               ^^^^^^^^^^^^^^^^^
      File "/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/chaosaws/iam/actions.py", line 34, in create_policy
        raise FailedActivity(f"failed creating a policy: {str(x)}")
    chaoslib.exceptions.ActivityFailed: chaoslib.exceptions.ActivityFailed: failed creating a policy: An error occurred (EntityAlreadyExists) when calling the CreatePolicy operation: A policy called newer-chaos-policy-for-collins already exists. Duplicate names are not allowed.
[31m[2023-08-31 09:39:03 ERROR] [activity:245][39m   => failed: chaoslib.exceptions.ActivityFailed: failed creating a policy: An error occurred (EntityAlreadyExists) when calling the CreatePolicy operation: A policy called newer-chaos-policy-for-collins already exists. Duplicate names are not allowed.
[36m[2023-08-31 09:39:03 DEBUG] [__init__:450][39m No controls to apply on 'activity'
[36m[2023-08-31 09:39:03 DEBUG] [__init__:450][39m No controls to apply on 'method'
[32m[2023-08-31 09:39:03 INFO] [run:964][39m Let's rollback...
[36m[2023-08-31 09:39:03 DEBUG] [__init__:450][39m No controls to apply on 'rollback'
[32m[2023-08-31 09:39:03 INFO] [rollback:31][39m No declared rollbacks, let's move on.
[36m[2023-08-31 09:39:03 DEBUG] [__init__:450][39m No controls to apply on 'rollback'
[32m[2023-08-31 09:39:03 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-08-31 09:39:03 DEBUG] [__init__:450][39m No controls to apply on 'experiment'
[36m[2023-08-31 09:39:03 DEBUG] [__init__:103][39m Cleaning up controls
[36m[2023-08-31 09:39:03 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-08-31 09:42:25 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-08-31 09:42:25 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-08-31 09:42:25 DEBUG] [cli:119][39m Using settings file '/Users/collinsorighose/.chaostoolkit/settings.yaml'
[36m[2023-08-31 09:42:26 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/Users/collinsorighose/.chaostoolkit/settings.yaml'.
[36m[2023-08-31 09:42:26 DEBUG] [__init__:450][39m No controls to apply on 'loader'
[36m[2023-08-31 09:42:26 DEBUG] [__init__:450][39m No controls to apply on 'loader'
[36m[2023-08-31 09:42:26 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-08-31 09:42:26 DEBUG] [caching:35][39m Cached 1 activities
[32m[2023-08-31 09:42:26 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-08-31 09:42:26 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-08-31 09:42:26 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-08-31 09:42:26 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-08-31 09:42:26 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-08-31 09:42:26 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-08-31 09:42:26 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-08-31 09:42:26 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-08-31 09:42:26 DEBUG] [caching:35][39m Cached 1 activities
[36m[2023-08-31 09:42:26 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-08-31 09:42:26 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-08-31 09:42:26 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-08-31 09:42:26 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2023-08-31 09:42:26 INFO] [run:369][39m Running experiment: create-a-policy
[36m[2023-08-31 09:42:26 DEBUG] [__init__:64][39m Initializing controls
[32m[2023-08-31 09:42:26 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-08-31 09:42:26 INFO] [run:400][39m Rollbacks strategy: default
[32m[2023-08-31 09:42:26 INFO] [run:408][39m No steady state hypothesis defined. That's ok, just exploring.
[36m[2023-08-31 09:42:26 DEBUG] [__init__:450][39m No controls to apply on 'experiment'
[32m[2023-08-31 09:42:26 INFO] [run:684][39m Playing your experiment's method now...
[36m[2023-08-31 09:42:26 DEBUG] [__init__:450][39m No controls to apply on 'method'
[36m[2023-08-31 09:42:26 DEBUG] [__init__:450][39m No controls to apply on 'activity'
[32m[2023-08-31 09:42:26 INFO] [activity:215][39m Probe: create-a-new-policy
[36m[2023-08-31 09:42:26 DEBUG] [python:33][39m Activity 'create-a-new-policy' loaded from '/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/chaosaws/iam/actions.py'
[36m[2023-08-31 09:42:26 DEBUG] [__init__:76][39m Using AWS region 'eu-west-2'
[36m[2023-08-31 09:42:26 DEBUG] [__init__:85][39m Client will be using profile 'default' from boto3 session
[36m[2023-08-31 09:42:27 DEBUG] [activity:237][39m   => succeeded with '{'Policy': {'PolicyName': '1-chaos-policy-for-collins', 'PolicyId': 'ANPAZ6VZFIT5OHUWH3DWO', 'Arn': 'arn:aws:iam::684361860346:policy/corighose/collinsefe/1-chaos-policy-for-collins', 'Path': '/corighose/collinsefe/', 'DefaultVersionId': 'v1', 'AttachmentCount': 0, 'PermissionsBoundaryUsageCount': 0, 'IsAttachable': True, 'CreateDate': datetime.datetime(2023, 8, 31, 8, 42, 27, tzinfo=tzutc()), 'UpdateDate': datetime.datetime(2023, 8, 31, 8, 42, 27, tzinfo=tzutc())}, 'ResponseMetadata': {'RequestId': 'f719c4b6-10f2-4745-ad88-437be0248551', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'f719c4b6-10f2-4745-ad88-437be0248551', 'content-type': 'text/xml', 'content-length': '829', 'date': 'Thu, 31 Aug 2023 08:42:27 GMT'}, 'RetryAttempts': 0}}'
[36m[2023-08-31 09:42:27 DEBUG] [__init__:450][39m No controls to apply on 'activity'
[36m[2023-08-31 09:42:27 DEBUG] [__init__:450][39m No controls to apply on 'method'
[32m[2023-08-31 09:42:27 INFO] [run:964][39m Let's rollback...
[36m[2023-08-31 09:42:27 DEBUG] [__init__:450][39m No controls to apply on 'rollback'
[32m[2023-08-31 09:42:27 INFO] [rollback:31][39m No declared rollbacks, let's move on.
[36m[2023-08-31 09:42:27 DEBUG] [__init__:450][39m No controls to apply on 'rollback'
[32m[2023-08-31 09:42:27 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-08-31 09:42:27 DEBUG] [__init__:450][39m No controls to apply on 'experiment'
[36m[2023-08-31 09:42:27 DEBUG] [__init__:103][39m Cleaning up controls
[36m[2023-08-31 09:42:27 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-08-31 09:46:34 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-08-31 09:46:34 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-08-31 09:46:34 DEBUG] [cli:119][39m Using settings file '/Users/collinsorighose/.chaostoolkit/settings.yaml'
[36m[2023-08-31 09:46:34 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/Users/collinsorighose/.chaostoolkit/settings.yaml'.
[36m[2023-08-31 09:46:34 DEBUG] [__init__:450][39m No controls to apply on 'loader'
[36m[2023-08-31 09:46:34 DEBUG] [__init__:450][39m No controls to apply on 'loader'
[36m[2023-08-31 09:46:34 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-08-31 09:46:34 DEBUG] [caching:35][39m Cached 1 activities
[32m[2023-08-31 09:46:34 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-08-31 09:46:34 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-08-31 09:46:34 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-08-31 09:46:34 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-08-31 09:46:35 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-08-31 09:46:35 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-08-31 09:46:35 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-08-31 09:46:35 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-08-31 09:46:35 DEBUG] [caching:35][39m Cached 1 activities
[36m[2023-08-31 09:46:35 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-08-31 09:46:35 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-08-31 09:46:35 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-08-31 09:46:35 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2023-08-31 09:46:35 INFO] [run:369][39m Running experiment: attach-a-policy
[36m[2023-08-31 09:46:35 DEBUG] [__init__:64][39m Initializing controls
[32m[2023-08-31 09:46:35 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-08-31 09:46:35 INFO] [run:400][39m Rollbacks strategy: default
[32m[2023-08-31 09:46:35 INFO] [run:408][39m No steady state hypothesis defined. That's ok, just exploring.
[36m[2023-08-31 09:46:35 DEBUG] [__init__:450][39m No controls to apply on 'experiment'
[32m[2023-08-31 09:46:35 INFO] [run:684][39m Playing your experiment's method now...
[36m[2023-08-31 09:46:35 DEBUG] [__init__:450][39m No controls to apply on 'method'
[36m[2023-08-31 09:46:35 DEBUG] [__init__:450][39m No controls to apply on 'activity'
[32m[2023-08-31 09:46:35 INFO] [activity:215][39m Probe: attach-role-policy
[36m[2023-08-31 09:46:35 DEBUG] [python:33][39m Activity 'attach-role-policy' loaded from '/Users/collinsorighose/opt/anaconda3/envs/demo/lib/python3.11/site-packages/chaosaws/iam/actions.py'
[36m[2023-08-31 09:46:35 DEBUG] [__init__:76][39m Using AWS region 'eu-west-2'
[36m[2023-08-31 09:46:35 DEBUG] [__init__:85][39m Client will be using profile 'default' from boto3 session
[36m[2023-08-31 09:46:38 DEBUG] [activity:237][39m   => succeeded with '{'ResponseMetadata': {'RequestId': '8b525524-eb70-4026-807a-86bb2d1d8077', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '8b525524-eb70-4026-807a-86bb2d1d8077', 'content-type': 'text/xml', 'content-length': '212', 'date': 'Thu, 31 Aug 2023 08:46:37 GMT'}, 'RetryAttempts': 0}}'
[36m[2023-08-31 09:46:38 DEBUG] [__init__:450][39m No controls to apply on 'activity'
[36m[2023-08-31 09:46:38 DEBUG] [__init__:450][39m No controls to apply on 'method'
[32m[2023-08-31 09:46:38 INFO] [run:964][39m Let's rollback...
[36m[2023-08-31 09:46:38 DEBUG] [__init__:450][39m No controls to apply on 'rollback'
[32m[2023-08-31 09:46:38 INFO] [rollback:31][39m No declared rollbacks, let's move on.
[36m[2023-08-31 09:46:38 DEBUG] [__init__:450][39m No controls to apply on 'rollback'
[32m[2023-08-31 09:46:38 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-08-31 09:46:38 DEBUG] [__init__:450][39m No controls to apply on 'experiment'
[36m[2023-08-31 09:46:38 DEBUG] [__init__:103][39m Cleaning up controls
[36m[2023-08-31 09:46:38 DEBUG] [caching:42][39m Clearing activities cache
